# -*- coding: utf-8 -*-
"""Atividade 2 Py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1swpjeDkusMtn6CYw8aOK0FPRqGonmnXB

#Arquivo .py GitHub https://github.com/iSKGtm/ProzExe

#ATIVIDADE

Faça uma função calculadora de dois números com três parâmetros: os dois primeiros serão os números da operação e o terceiro será a entrada que definirá a operação a ser executada. Considera a seguinte definição:

Soma
Subtração
Multiplicação
Divisão
Caso seja inserido um número de operação que não exista, o resultado deverá ser 0.
"""

def soma(x, y):
  return x + y

def subt(x, y):
  return x - y

def multi(x, y):
  return x * y

def divis(x, y):
  return x / y

print("1. Adição")
print("2. Subtração")
print("3. Multiplicação")
print("4. Divisão")

while True:
  escolha = input("Selecione a operação acima: ")

  if escolha in ('1', '2', '3', '4'):
    try:
      num1 = float(input("Escolha o primeiro número: "))
      num2 = float(input("Escolha o segundo número: "))
    except ValueError:
      print("Por favor, digite um número novamente.")
      continue

    if escolha == '1':
      print(num1, "+", num2, "=", soma(num1, num2))

    elif escolha == '2':
      print(num1, "-", num2, "=", subt(num1, num2))

    elif escolha == '3':
      print(num1, "*", num2, "=", multi(num1, num2))

    elif escolha == '4':
      print(num1, "/", num2, "=", divis(num1, num2))
    break