# -*- coding: utf-8 -*-
"""Atividade 4 Py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GCR_at8F1wZk6A8MimmsX_9_qII1ybiE

#Atividade
#Arquivo .py GitHub https://github.com/iSKGtm/ProzExe

Desenvolva um programa que recebe do usuário nome completo e ano de nascimento que seja entre 1922 e 2021.
A partir dessas informações, o sistema mostrará o nome do usuário e a idade que completou, ou completará, no ano atual (2022).

Caso o usuário não digite um número ou apareça um inválido no campo do ano, o sistema informará o erro e continuará perguntando até que um valor correto seja preenchido.
"""

import datetime

anoAtual = datetime.date.today().year
nome = input("Digite seu nome: ")
anoLimitPos = anoAtual
anoLimitAnt = anoAtual - 120

anoNasc = input("Digite o ano em que você nasceu: ")
anoNasc = int(anoNasc)

if(anoNasc >= anoLimitAnt) and (anoNasc <= anoAtual):
  print("Calculando sua idade...")
  print("Olá", nome, "atualmente, você tem:", idade, "de idade.")
else:
   print("Por favor, verifique seus dados e tente novamente...")