# -*- coding: utf-8 -*-
"""Exercicio 1 Py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ivzq7VMNzqGUI7CvN3mdSAme_1utIex

Precisamos imprimir um número para cada andar de um hotel de 20 andares. Porém, o dono do hotel é supersticioso e optou por não ter um 13ro andar.

Escreva um código que imprima todos os números exceto o número 13.
Escreva mais dois códigos que resolvam o mesmo problema, mas dessa vez usando os outros dois tipos de laços de repetição aprendidos.

Como desafio, imprima eles em ordem decrescente (20, 19, 18...)

#EXE N1 FOR DECRESCENTE
"""

import time

andarInicial = 20

andarFinal = 0

print("Quantidade de Andares: 20")

for a in range(andarInicial, andarFinal, -1):
  time.sleep(0.3)
  if(a == 13):
    print("|| Andar Indisponível ||")
    continue
  aStr = str(a)
  print("Andar Número: "+ aStr)

print("Fim dos Andares")

"""#EXE N2 WHILE DECRESCENTE"""

import time

andarInicial = 20
a = 20

print("Quantidade de Andares: 20")

while a > 0:
  time.sleep(0.3)
  if(a == 13):
    print("|| Andar Indisponível ||")
    a = a - 1
    continue
  aStr = str(a)
  print("Andar Número: "+ aStr)
  a = a - 1

print("Fim dos Andares")

"""#EX N3 FOR CRESCENTE"""

import time

andarInicial = 1

andarFinal = 21

print("Quantidade de Andares: 20")

for a in range(andarInicial, andarFinal, +1):
  time.sleep(0.3)
  if(a == 13):
    print("|| Andar Indisponível ||")
    continue
  aStr = str(a)
  print("Andar Número: "+ aStr)

print("Fim dos Andares")

"""#EX N4 WHILE CRESCENTE"""

import time

andarInicial = 1
a = 1

print("Quantidade de Andares: 20")

while a < 21:
  time.sleep(0.3)
  if(a == 13):
    print("|| Andar Indisponível ||")
    a = a + 1
    continue
  aStr = str(a)
  print("Andar Número: "+ aStr)
  a = a + 1

print("Fim dos Andares")